### PR TITLE
Add sel_clear thread to enable "SEL auto injection" function 

### PR DESCRIPTION
**Pull request by sharkconi**
OpenIPMI will add "sel_list" sub command. ipmi_sim.py will check this new command result to decide whether add a new SEL message or not

### CODE REVIEW

**Comment by sharkconi** [comment]
@turtle-fly @fub2 @xiar @PaynePei

**Comment by xiar** [comment]
Can one of the admins verify this patch?

**Comment by turtle-fly** [comment]
:+1:

**Comment by fub2** [comment]
:+1:

**Comment by emcinfrasim** [comment]
```
******* IDIC_pull_request_trigger ******* 
TestName: T46139_idic_IPMISIMSensorAccessible 
ErrorMessage: BMC IPMI_SIM sensor command of a node not accessible. Rack is vRack1, Node is vbmc_s2600tp_pr.ova_1461901863.35, BMC IP is: 192.168.187.119,  BMC IPMI_SIM sensor command of a node not accessible. Rack is vRack1, Node is vbmc_s2600tp_pr.ova_1461901887.0, BMC IP is: 192.168.187.120 
TestName: T36706_idic_vBMCDataEmulation 
ErrorMessage: Node vbmc_s2600tp_pr.ova_1461901863.35 on rack vRack1 failed to set sensor 0x23 to mode fault status uc, node vBMC ip is 192.168.187.119, ipmitool return: SEL has no entries count=0, countstr=(null) ,  Node vbmc_s2600tp_pr.ova_1461901887.0 on rack vRack1 failed to set sensor 0x23 to mode fault status uc, node vBMC ip is 192.168.187.120, ipmitool return: SEL has no entries count=0, countstr=(null) 
TestName: T43943_idic_IPMISIMHelpAccessible 
ErrorMessage: BMC IPMI_SIM of a node not accessible. Rack is vRack1, Node is vbmc_s2600tp_pr.ova_1461901863.35, BMC IP is: 192.168.187.119,  BMC IPMI_SIM of a node not accessible. Rack is vRack1, Node is vbmc_s2600tp_pr.ova_1461901887.0, BMC IP is: 192.168.187.120 
TestName: T33227_idic_vBMCAddSelThroughSensor 
ErrorMessage: Nothing from vBMC. Node is vbmc_s2600tp_pr.ova_1461901863.35, BMC ip is: 192.168.187.119,  Nothing from vBMC. Node is vbmc_s2600tp_pr.ova_1461901887.0, BMC ip is: 192.168.187.120 
TestName: T33226_idic_vBMCAddSelThroughCommand 
ErrorMessage: Nothing from vBMC. Node is vbmc_s2600tp_pr.ova_1461901863.35, BMC ip is: 192.168.187.119,  Nothing from vBMC. Node is vbmc_s2600tp_pr.ova_1461901887.0, BMC ip is: 192.168.187.120 
TestName: T46140_idic_IPMISIMSelAccessible 
ErrorMessage: Nothing from vBMC. Node is vbmc_s2600tp_pr.ova_1461901863.35, BMC ip is: 192.168.187.119,  Nothing from vBMC. Node is vbmc_s2600tp_pr.ova_1461901887.0, BMC ip is: 192.168.187.120 
TestName: T46141_idic_IPMISIMHistoryAccessible 
ErrorMessage: BMC IPMI_SIM sensor command of a node not accessible. Rack is vRack1, Node is vbmc_s2600tp_pr.ova_1461901863.35, BMC IP is: 192.168.187.119,  BMC IPMI_SIM sensor command of a node not accessible. Rack is vRack1, Node is vbmc_s2600tp_pr.ova_1461901887.0, BMC IP is: 192.168.187.120 
```

**Comment by turtle-fly** [comment]
need to merge PR in openipmi first, then kick off test.

**Comment by sharkconi** [comment]
retest this please

**Comment by fub2** [comment]
Gotta merge this PR once all smoke tests pass. Understand there could be other way to resolve this and it would be great if we could continuously evaluate 2 alternatives. However, since most of servers exhibits behaviors of logging SEL on clearing SEL operation. We don't have to bother which would be most flexible one to filter out servers that are not exhibiting this behaviors. Let's simply stick to what has been worked out.

**Pull request merged**
