### PR TITLE
fix two idic issues

### PR DESCRIPTION
**Pull request by PaynePei**
1. ipmi_sim service not start 2.vpdu command changed

### CODE REVIEW

**Comment by xiar** [comment]
Can one of the admins verify this patch?

**Comment by emcinfrasim** [comment]
```
******* IDIC_pull_request_trigger ******* 
TestName: T43943_idic_IPMISIMHelpAccessible 
ErrorMessage: BMC IPMI_SIM of a node not accessible. Rack is vRack1, Node is vbmc_dell_r630_pr.ova_1467702705.43, BMC IP is: 192.168.132.95,  BMC IPMI_SIM of a node not accessible. Rack is vRack1, Node is vbmc_dell_r630_pr.ova_1467702687.57, BMC IP is: 192.168.132.96 
TestName: T46139_idic_IPMISIMSensorAccessible 
ErrorMessage: BMC IPMI_SIM sensor command is not accessible. Rack is vRack1, Node is vbmc_dell_r630_pr.ova_1467702705.43, BMC IP is: 192.168.132.95,  BMC IPMI_SIM sensor command is not accessible. Rack is vRack1, Node is vbmc_dell_r630_pr.ova_1467702687.57, BMC IP is: 192.168.132.96 
TestName: T46139_idic_IPMISIMSensorAccessible 
ErrorMessage: BMC IPMI_SIM sensor command is not accessible. Rack is vRack1, Node is vbmc_dell_r630_pr.ova_1467702705.43, BMC IP is: 192.168.132.95,  BMC IPMI_SIM sensor command is not accessible. Rack is vRack1, Node is vbmc_dell_r630_pr.ova_1467702687.57, BMC IP is: 192.168.132.96 
```

**Comment by PaynePei** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* IDIC_pull_request_trigger ******* 
TestName: T43943_idic_IPMISIMHelpAccessible 
ErrorMessage: BMC IPMI_SIM of a node not accessible. Rack is vRack1, Node is vbmc_s2600tp_pr.ova_1467771857.29, BMC IP is: 192.168.132.158,  BMC IPMI_SIM of a node not accessible. Rack is vRack1, Node is vbmc_s2600tp_pr.ova_1467771883.16, BMC IP is: 192.168.132.155 
TestName: T46139_idic_IPMISIMSensorAccessible 
ErrorMessage: BMC IPMI_SIM sensor command is not accessible. Rack is vRack1, Node is vbmc_s2600tp_pr.ova_1467771857.29, BMC IP is: 192.168.132.158,  BMC IPMI_SIM sensor command is not accessible. Rack is vRack1, Node is vbmc_s2600tp_pr.ova_1467771883.16, BMC IP is: 192.168.132.155 
TestName: T46139_idic_IPMISIMSensorAccessible 
ErrorMessage: BMC IPMI_SIM sensor command is not accessible. Rack is vRack1, Node is vbmc_s2600tp_pr.ova_1467771857.29, BMC IP is: 192.168.132.158,  BMC IPMI_SIM sensor command is not accessible. Rack is vRack1, Node is vbmc_s2600tp_pr.ova_1467771883.16, BMC IP is: 192.168.132.155 
```

**Comment by PaynePei** [comment]
@xiar smoke test pass, but the value will be set 0 forcefully if ipmi command fails, do you think it's reasonable?

**Comment by xiar** [comment]
+1

**Pull request merged**
