### PR TITLE
remove redfish from vnode

### PR DESCRIPTION
**Pull request by PaynePei**

### CODE REVIEW

**Comment by xiar** [comment]
Can one of the admins verify this patch?

**Comment by fub2** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* IDIC_pull_request_trigger ******* 
TestName: T46139_idic_IPMISIMSensorAccessible 
ErrorMessage: Failed to set up BMC sensor (id:0x30) value through IPMI_SIM. Rack is vRack1, Node is vbmc_dell_r730xd_pr.ova_1469499017.45, BMC IP is: 192.168.136.237,  Failed to set up BMC sensor (id:0x30) value through IPMI_SIM. Rack is vRack1, Node is vbmc_dell_r730xd_pr.ova_1469499000.58, BMC IP is: 192.168.129.144 
TestName: T46139_idic_IPMISIMSensorAccessible 
ErrorMessage: Failed to set up BMC sensor (id:0x30) value through IPMI_SIM. Rack is vRack1, Node is vbmc_dell_r730xd_pr.ova_1469499017.45, BMC IP is: 192.168.136.237,  Failed to set up BMC sensor (id:0x30) value through IPMI_SIM. Rack is vRack1, Node is vbmc_dell_r730xd_pr.ova_1469499000.58, BMC IP is: 192.168.129.144 
```

**Comment by fub2** [comment]
+1
Only failure in smoke test is:
46139	fail	Failed to set up BMC sensor (id:0x30) value through IPMI_SIM.

Merging this PR:

**Pull request merged**
