### PR TITLE
Fix history message queue doesn't show latest command when over 30 commands was run.

### PR DESCRIPTION
**Pull request by JuneZhou19**
@xiar @MarkMa001 @turtle-fly @PaynePei 

It fix ipmi_sim issue in ODR HWSIM-812.

### CODE REVIEW

**Comment by xiar** [comment]
Can one of the admins verify this patch?

**Comment by sharkconi** [comment]
+1

**Comment by fub2** [comment]
:100: :+1:  @JuneZhou19

**Comment by PaynePei** [comment]
retest this please

**Comment by JuneZhou19** [comment]
All checks passed. Can core committee help to merge if no concern? @xiar @MarkMa001 @turtle-fly

**Pull request merged**
