### PR TITLE
remove seabios to stop nodes rebooting

### PR DESCRIPTION
**Pull request by PaynePei**

### CODE REVIEW

**Comment by xiar** [comment]
Can one of the admins verify this patch?

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
@fub2 @xiar  bios behavior is expected in local test

**Comment by fub2** [comment]
@PaynePei what is going wrong in smoke test?

**Comment by PaynePei** [comment]
@fub2 memory of Jenkins is out during the test

**Comment by fub2** [comment]
+1

**Pull request merged**
