### PR TITLE
add retry mechanism to run ipmi_sim.py script

### PR DESCRIPTION
**Pull request by PaynePei**
@xiar @MarkMa001 please have a review

### CODE REVIEW

**Comment by xiar** [comment]
Can one of the admins verify this patch?

**Comment by sharkconi** [comment]
+1

**Comment by fub2** [comment]
Is it a workaround? If it requires more testing to verify, mine is +0

**Comment by PaynePei** [comment]
@fub2 this is not a workaround. but it's hard to be reproduced except daily CI test. if the smoke test passes, it's better to merge it today and then check the result of daily CI tomorrow

**Comment by emcinfrasim** [comment]
```
******* IDIC_pull_request_trigger ******* 
TestName: T33250_idic_KCSSensorList 
ErrorMessage: Failed on local IPMI command ipmitool sensor list, return:  
```

**Comment by PaynePei** [comment]
rerun the failed case and no issue

**Comment by PaynePei** [comment]
17:28:21.426                  task:  Case T33250_idic_KCSSensorList with data (1/1) is done, result: pass, error code:

**Comment by xiar** [comment]
retest this please

**Comment by fub2** [comment]
+1

**Comment by emcinfrasim** [comment]
```
******* IDIC_pull_request_trigger ******* 
TestName: T33250_idic_KCSSensorList 
ErrorMessage: Failed on local IPMI command ipmitool sensor list, return:  
```

**Pull request merged**
