### PR TITLE
Update openipmi branch

### PR DESCRIPTION
**Pull request by XiaowenJiang**
change BRANCH to to "infrasim-openipmi-2.0.22"

### CODE REVIEW

**Comment by xiar** [comment]
Can one of the admins verify this patch?

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please!!!

**Comment by XiaowenJiang** [comment]
retest this please...( die

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* IDIC_pull_request_trigger ******* 
TestName: T33250_idic_KCSSensorList 
ErrorMessage: Fail to get host access: Fail to get node vbmc_s2600wtt_pr.ova_1473303846.84's host IP in 300s, check if vSwith's promiscuous mode is "Accept" 
```

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by emcinfrasim** [comment]
retest this please

**Comment by XiaowenJiang** [comment]
retest this please

**Comment by emcinfrasim** [comment]
```
******* IDIC_pull_request_trigger ******* 
TestName: T46139_idic_IPMISIMSensorAccessible 
ErrorMessage: BMC IPMI_SIM sensor command is not accessible. Rack is vRack1, Node is vbmc_dell_c6320_pr.ova_1473384434.92, BMC IP is: 192.168.134.164 
```

**Comment by xiar** [comment]
retest this  please

**Comment by emcinfrasim** [comment]
```
******* IDIC_pull_request_trigger ******* 
TestName: Puffer Test 
ErrorMessage:  there is no test result  
```

**Comment by fub2** [comment]
+1

**Pull request merged**
