### PR TITLE
Update Qemu to v2.6.0 release

### PR DESCRIPTION
**Pull request by sharkconi**

### CODE REVIEW

**Comment by sharkconi** [comment]
@fub2 @turtle-fly @xiar @PaynePei @JuneZhou19

**Comment by xiar** [comment]
Can one of the admins verify this patch?

**Comment by turtle-fly** [comment]
@PaynePei the smoke CI fail on deploy, one possible problem seems PDU information is not well generated.

**Comment by PaynePei** [comment]
retest this please

**Comment by fub2** [comment]
is this PR still required? Has latest build included qemu v2.6.0? @sharkconi @PaynePei

**Comment by turtle-fly** [comment]
retest this please

**Pull request closed without merging**
