### PR TITLE
update lanserv.init for ipmi_sim.py issue:

### PR DESCRIPTION
**Pull request by PaynePei**
1.add sleep time between commands run 2.clear the error log

### CODE REVIEW

**Comment by PaynePei** [comment]
@xiar @MarkMa001 @fub2 please help to review

**Comment by sharkconi** [comment]
+1

**Comment by xiar** [comment]
Can one of the admins verify this patch?

**Comment by fub2** [comment]
Ship it! Keep up effort fighting this bug!

**Comment by xiar** [comment]
:+1:

**Pull request merged**
