### PR TITLE
Use udp protocal for socat/qemu 9003 port connect

### PR DESCRIPTION
**Pull request by sharkconi**

### CODE REVIEW

**Comment by xiar** [comment]
Can one of the admins verify this patch?

**Comment by sharkconi** [comment]
@fub2 @XiaowenJiang @xiar @turtle-fly @PaynePei

**Comment by fub2** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by fub2** [comment]
retest this please

**Comment by PaynePei** [comment]
retest this please

**Comment by PaynePei** [comment]
+1

**Comment by XiaowenJiang** [comment]
+1

**Pull request merged**
