### PR TITLE
Fix typo in IPMI_SIM command response.

### PR DESCRIPTION
**Pull request by JuneZhou19**
@fub2 @xiar @turtle-fly @MarkMa001

### CODE REVIEW

**Comment by sharkconi** [comment]
好眼力!

**Comment by xiar** [comment]
Can one of the admins verify this patch?

**Comment by turtle-fly** [comment]
+1 and this should have same test result with previous build.

**Comment by fub2** [comment]
+1

**Comment by turtle-fly** [comment]
@JuneZhou19 why there is such a sudden conflict...

**Comment by JuneZhou19** [comment]
@turtle-fly what conflict?

**Comment by turtle-fly** [comment]
Github shows "This branch has conflicts that must be resolved"

**Comment by xiar** [comment]
Can one of the admins verify this patch?

**Comment by turtle-fly** [comment]
good to go

**Pull request merged**
